name: Subdomain Scanner - Passive - Findomain

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BINARY_FINDOMAIN: "https://github.com/Findomain/Findomain/releases/download/10.0.1/findomain-linux.zip"
      DOMAIN_VALUE: "yape.com.pe"

    steps:
      - uses: actions/checkout@v4

      - name: Run findomain
        run: |
          wget -O /tmp/findomain.zip ${{ env.BINARY_FINDOMAIN }}
          unzip /tmp/findomain.zip -d /tmp
          /tmp/findomain -q -t ${{ env.DOMAIN_VALUE }} > /tmp/findomain.txt
        
      #- name: Pull changes
      #  run: |
      #    git pull --rebase origin main

      - name: Save results into repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Trae cambios del remoto primero (evita "fetch first")
          git pull --rebase origin main

          # Guarda/actualiza el txt
          mkdir -p results
          cp /tmp/findomain.txt results/findomain.txt

          # Commit solo si hay cambios (evita "nothing to commit")
          git add results/findomain.txt
          git diff --cached --quiet || git commit -m "Update subdomains results"

          # Push
          git push origin main