name: Subdomain Scanner - Passive - Findomain

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BINARY_FINDOMAIN: "https://github.com/Findomain/Findomain/releases/download/10.0.1/findomain-linux.zip"
      DOMAIN_VALUE: "yape.com.pe"

    steps:
      - uses: actions/checkout@v4

      - name: Run findomain
        run: |
          wget -O /tmp/findomain.zip ${{ env.BINARY_FINDOMAIN }}
          unzip /tmp/findomain.zip -d /tmp
          /tmp/findomain -q -t ${{ env.DOMAIN_VALUE }} > /tmp/findomain.txt


      - name: Delete old file if exists
        run: |
          if [ -f results/assetfinder.txt ]; then
            rm results/assetfinder.txt
            echo "Old file deleted"
          else
            echo "File does not exist"
          fi

      - name: Save results into repo
        run: |
          mkdir -p results
          cp /tmp/findomain.txt results/findomain.txt
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add results/findomain.txt
          git commit -m "Update subdomains results"
          git push